### ISSUE TITLE
trying to used code with Satorius Practium 313-1S

### ISSUE THREAD

**Issue by seacuello** [sanmai/usb-scale-reader#1]
Hello -

I cloned the directory and made the c file, then attempted to run using 'sudo ./usbscale /dev/hidraw3', but there was no hidraw3.  A quick glance showed that hidraw0 and hidraw1 exist, and I tried both of those but the program just stalls.

I have not changed any files, and am unsure exactly how to adjust the rules file to accept this scale.  Can you explain to me how to do so??  

Thanks!

**Comment by seacuello** [comment]
Hi after some more reseach i found that my devise is hidraw0.  I tried this terminology in the usage and recieved the error 'unable to open /dev/hidraw0'

Is there something missing in my rules files that may need to be adjusted?

**Comment by sanmai** [comment]
Did you run it with sudo? You could possibly have a primitive permission problem.

As said in erjiang/usbscale#16 if you can see gibberish coming from the device, and if it follows the protocol, then this program should show you weight, or at least something.

Other chance is that you device could have a proprietary protocol, then nor my program nor erjiang/usbscale would help. 

The latter tries to access a device directly, not by means of `/dev/hidrawX`, which way is prone to unknown errors. There were issues with that in the past. But you don't have to specify a device directly.

On the other hand my program does no magic, and will read from any device. If it could read your scale, and erjiang/usbscale could not, then the latter could be fixed to read your scale.

If my program couldn't read your scale, then erjiang/usbscale too will never be able to.

Is there's something unclear in my explanation?

**Comment by seacuello** [comment]
@ sanmai - yes i did run with sudo.. When you say follows the protocol in your 2nd paragraph, what type of protocol are you referring to?

Also thanks again for your help and info which has been teaching me a lot..

**Comment by sanmai** [comment]
I believe here was a reference I used: http://www.usb.org/developers/hidpage/pos1_02.pdf

**Comment by sanmai** [comment]
Let's move further discussion to erjiang/usbscale#16
