### ISSUE TITLE
Documentation & using it in POS

### ISSUE THREAD

**Issue by twf-nikhila** [sanmai/usb-scale-reader#2]
Hello @sanmai 

Do you have documentation on integrating it with a web application?

**Comment by sanmai** [comment]
Isn't the [README.md](https://github.com/sanmai/usb-scale-reader/blob/master/README.md) sufficient?

**Comment by develamit** [comment]
Could you please share the exact stamps.com model? Is it Model 510?
Thanks,

**Comment by sanmai** [comment]
I have Stamps SDC 550 5LB for testing purposes, but generally DYMO M25 much more robust, can handle greater weights, and easier to source.
